spring:
  data:
    elasticsearch:
      client:
          WIRE: INFO


logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE:TRACE:
